[package]
name = "nybl-rust-embedding-examples"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nybl = { package = "nybl-lang", path = "../../nybl" }
nybl-vm = { path = "../../nybl-vm" }

[build-dependencies]
nybl-compile = { path = "../../nybl-compile" }
